### ISSUE TITLE
node_exporter change default port 9100

### ISSUE THREAD

**Issue by JJena** [voxpupuli/puppet-prometheus#708] opened 2023-12-12 16:42 UTC
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7
- Distribution: CentOS 7
- Module version: 13.4.0

## How to reproduce (e.g Puppet code you use)
Can't find option to change the default port 9100 where metrics are published. Node_exporter.pp also has no parameter to change the port. Tried scrape_port parameter but that doesn't change the port.

## What are you seeing
Can't override default port 9100

## What behaviour did you expect instead
Update README how to override default node_exporter port

**Comment by maxkerp** [comment] 2024-04-16 14:45
I just tripped over this myself today and for any other poor souls out there:

`scrape_port` is apparently only used for a `scrape_job` when you use `$export_scrape_job`, which in turn creates a scrape-job on the "real" prometheus host. That's how I understand it.

See:
https://github.com/voxpupuli/puppet-prometheus/blob/master/manifests/daemon.pp#L284

What you wanna do is use `--web.listen-address` in `extra_options` to be passed to the binary.

```puppet
  class { 'prometheus::node_exporter':
    version            => '1.7.0',
    collectors_enable  => ['systemd'],
    extra_options      => '--web.listen-address=":9101" --collector.systemd.unit-include=(.*).service',
  }
```

This does work and is mentioned for some exporters on the puppet-forge docs page, but it's hard to find and I would have expected it to be a parameter (`listen_port`?) too.

Unfortunately this isn't a consistent interface for the exporters. If you use the `postgres_exporter` for example, the parameter you need to use is only `options`.

```puppet
class { 'prometheus::postgres_exporter' :
  options              => '--web.listen-address=":9102"',
  group                => 'postgres',
  user                 => 'postgres',
  postgres_auth_method => 'custom',
  data_source_custom   => {
    'DATA_SOURCE_NAME' => 'user=postgres host=/var/run/postgresql/ sslmode=disable',
  },
}
```

**Comment by TheMeier** [comment] 2024-05-25 17:16
Duplicate of #692

**Closed as completed by TheMeier** 2024-05-25 17:16 UTC
Labels: skip-changelog
